### 랜덤 포레스트 모델
- Decision Tree모델이 여러개 모여서 집단 지성을 이루는 모델
- off the record : 겁나 많은 트리모델 가져다가 예측시키고 투표 시킴 / 많은 값이 나오면 정답 당선

In [1]:
# 필요한 라이브러리 가져오기
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
# 데이터 확보
# 데이터를 가지고 있다
# data = pd.read_csv() - 파일 가져오기
# 여기는 학습데이터 사용할 거임
from sklearn.datasets import load_iris

In [3]:
# 학습 데이터이기 때문에 여기는 생략 가능
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
# 문제 : data
# 정답 : target
# 설명서 : DESCR
# 특성 이름 : feture_names
# 정답 이름 : target_names

In [7]:
iris.data
# 150개의 데이터 / 4가지의 특성

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
# 1. 가독성을 위해 문제데이터 데이터프레임으로 만들기
iris_df = pd.DataFrame(iris.data, columns = iris.feature_names)
iris_df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [39]:
# 2. 정답과 문제를 묶어서 섞은다음 데이터 분할하기
# 훈련셋 평가셋으로 데이터를 분할
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_df, iris.target,
                                                   test_size = 0.3,
                                                   random_state = 5
                                                   )

In [40]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
126                6.2               2.8                4.8               1.8
61                 5.9               3.0                4.2               1.5
124                6.7               3.3                5.7               2.1
117                7.7               3.8                6.7               2.2
20                 5.4               3.4                1.7               0.2
..                 ...               ...                ...               ...
8                  4.4               2.9                1.4               0.2
73                 6.1               2.8                4.7               1.2
144                6.7               3.3                5.7               2.5
118                7.7               2.6                6.9               2.3
99                 5.7               2.8                4.1               1.3

[105 rows x 4 columns]

In [41]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((105, 4), (45, 4), (105,), (45,))

In [42]:
np.bincount(y_train)

array([35, 34, 36], dtype=int64)

In [ ]:
# 랜덤 포레스트 모델을 가져오자!!!(중요)

In [90]:
# 질문 랜덤포레스튼 무슨 기반 모델 - 앙상블 / 트리기반 모델
from sklearn.ensemble import RandomForestClassifier

In [44]:
# 모델 객체 생성
# 변수에 담아주기
rf_model = RandomForestClassifier() # 하이퍼 파라미터 조절 X / 기본 모델

In [45]:
# 교차검증 - 예상 성능 확인해보기
from sklearn.model_selection import cross_val_score

rs = cross_val_score(rf_model, X_train, y_train, cv = 5)
print(rs)
print(rs.mean())

[1.         0.9047619  1.         0.9047619  0.95238095]
0.9523809523809523


In [46]:
# 모델 학습 및 평가
rf_model.fit(X_train, y_train)

RandomForestClassifier()

In [47]:
rf_model.score(X_train, y_train)

1.0

In [48]:
rf_model.score(X_test, y_test)

0.9333333333333333

### 일반화
- 훈련 데이터 성능이 조금 떨어지더라도 평가 성능이 훈련데이터와 비슷하게 나오는 상황
- 일반화 성능을 끌어올리는게 머신러닝의 최종 목표

In [49]:
from sklearn.model_selection import GridSearchCV

In [52]:
# 하이퍼 파라미터 조절
# 내가 하이퍼 파라미터 뭉텡이를 던져주면 조합식을 짜서 최적의 조합을 짜줌
# 이때 사용하는건 교차검증 점수
param = { 'n_estimators' : [100, 500, 1000, 1500],
          'max_depth': range(1,6),
          'min_samples_split': range(1,6),
          'min_samples_leaf' : range(1,6)

        }

grid_model = GridSearchCV(rf_model, param, n_jobs=-1, cv = 5)

In [53]:
grid_model.fit(X_train, y_train)

C:\Users\smhrd\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
500 fits failed out of a total of 2500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\smhrd\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\smhrd\anaconda3\Lib\site-packages\sklearn\ensemble\_forest.py", line 340, in fit
    self._validate_params()
  File "C:\Users\smhrd\anaconda3\Lib\site-packages\sklearn\base.py", line 600, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\smhrd\anaconda3\Lib\site-pac

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': range(1, 6),
                         'min_samples_leaf': range(1, 6),
                         'min_samples_split': range(1, 6),
                         'n_estimators': [100, 500, 1000, 1500]})

In [54]:
grid_model.best_score_ # 최적 파라미터로 찾은 교차검증 점수

0.9619047619047618

In [55]:
grid_model.best_params_ # 최적 파라미터 목록

{'max_depth': 1,
 'min_samples_leaf': 1,
 'min_samples_split': 4,
 'n_estimators': 1000}

In [56]:
grid_model.best_estimator_ # 최적 파라미터 목록을 적용한 모델

RandomForestClassifier(max_depth=1, min_samples_split=4, n_estimators=1000)

In [57]:
best_model = grid_model.best_estimator_

In [58]:
best_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=1, min_samples_split=4, n_estimators=1000)

In [59]:
best_model.score(X_train, y_train)

0.9619047619047619

In [60]:
best_model.score(X_test, y_test)

0.9555555555555556

In [61]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
126                6.2               2.8                4.8               1.8
61                 5.9               3.0                4.2               1.5
124                6.7               3.3                5.7               2.1
117                7.7               3.8                6.7               2.2
20                 5.4               3.4                1.7               0.2
..                 ...               ...                ...               ...
8                  4.4               2.9                1.4               0.2
73                 6.1               2.8                4.7               1.2
144                6.7               3.3                5.7               2.5
118                7.7               2.6                6.9               2.3
99                 5.7               2.8                4.1               1.3

[105 rows x 4 columns]

In [68]:
pre = best_model.predict([[5.6, 3.0, 6.2, 1.1]]) #새로운 데이터를 입력해서 값 예측하기
pre

C:\Users\smhrd\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [71]:
iris.target_names[pre[0]]

'versicolor'

In [88]:
pre_per = best_model.predict_proba([[3.1, 3.3, 4.2, 1.4]])

C:\Users\smhrd\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [89]:
pre_per = best_model.predict_proba([[3.1, 3.3, 4.2, 1.4]])
print(f"방금전에 입력하신 붓꽃 품종의 종류는{pre_per.max() * 100: .2f}% 확률로 {iris.target_names[pre_per.argmax()]}입니다.")

방금전에 입력하신 붓꽃 품종의 종류는 45.07% 확률로 versicolor입니다.
